#
# CMakeLists.txt -- CMake build system for irccd
#
# Copyright (c) 2013, 2014, 2015 David Demelier <markand@malikania.fr>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set(
	COMMAND_SOURCES
	${CMAKE_CURRENT_LIST_DIR}/Command.cpp
	${CMAKE_CURRENT_LIST_DIR}/Command.h
	${CMAKE_CURRENT_LIST_DIR}/ChannelNotice.cpp
	${CMAKE_CURRENT_LIST_DIR}/ChannelNotice.h
	${CMAKE_CURRENT_LIST_DIR}/Invite.cpp
	${CMAKE_CURRENT_LIST_DIR}/Invite.h
	${CMAKE_CURRENT_LIST_DIR}/Join.cpp
	${CMAKE_CURRENT_LIST_DIR}/Join.h
	${CMAKE_CURRENT_LIST_DIR}/Kick.cpp
	${CMAKE_CURRENT_LIST_DIR}/Kick.h
	${CMAKE_CURRENT_LIST_DIR}/Me.cpp
	${CMAKE_CURRENT_LIST_DIR}/Me.h
	${CMAKE_CURRENT_LIST_DIR}/Message.cpp
	${CMAKE_CURRENT_LIST_DIR}/Message.h
	${CMAKE_CURRENT_LIST_DIR}/Mode.cpp
	${CMAKE_CURRENT_LIST_DIR}/Mode.h
	${CMAKE_CURRENT_LIST_DIR}/Names.cpp
	${CMAKE_CURRENT_LIST_DIR}/Names.h
	${CMAKE_CURRENT_LIST_DIR}/Nick.cpp
	${CMAKE_CURRENT_LIST_DIR}/Nick.h
	${CMAKE_CURRENT_LIST_DIR}/Notice.cpp
	${CMAKE_CURRENT_LIST_DIR}/Notice.h
	${CMAKE_CURRENT_LIST_DIR}/Part.cpp
	${CMAKE_CURRENT_LIST_DIR}/Part.h
	${CMAKE_CURRENT_LIST_DIR}/Send.cpp
	${CMAKE_CURRENT_LIST_DIR}/Send.h
	${CMAKE_CURRENT_LIST_DIR}/Topic.cpp
	${CMAKE_CURRENT_LIST_DIR}/Topic.h
	${CMAKE_CURRENT_LIST_DIR}/UserMode.cpp
	${CMAKE_CURRENT_LIST_DIR}/UserMode.h
	${CMAKE_CURRENT_LIST_DIR}/Whois.cpp
	${CMAKE_CURRENT_LIST_DIR}/Whois.h
)

source_group(command FILES ${COMMAND_SOURCES})
